In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

In [ ]:
df = pd.DataFrame({'min_temp':[20,21,22.3,34],'max_temp':[21,23,24.5,35]})
df.head()

min_temp  max_temp
0      20.0      21.0
1      21.0      23.0
2      22.3      24.5
3      34.0      35.0

In [ ]:
X = df[['min_temp']]
y = df[['max_temp']]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
mlp = MLPRegressor(hidden_layer_sizes=(2),activation='relu',max_iter=1000)

In [ ]:
mlp.fit(X_scaled,y)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=2, max_iter=1000)

In [ ]:
iter = 2
for i in range(iter):
  mlp.fit(X_scaled,y)
  hidden_layer_weights = mlp.coefs_[0]
  hidden_layer_bias = mlp.intercepts_[0]
  output_layer_weights = mlp.coefs_[1]
  output_layer_bias = mlp.intercepts_[1]
  print(hidden_layer_weights)
  print(hidden_layer_bias)
  print(output_layer_weights)
  print(output_layer_bias)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 0.09707556 -0.00268592]]
[-0.19359879 -0.31213243]
[[-1.21840046]
 [-0.19788042]]
[0.28361219]
[[ 1.80710181 -2.15199052]]
[1.27666053 0.69119917]
[[1.57226136]
 [2.7778627 ]]
[0.42550625]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
df = pd.DataFrame({'even':[2,4,6,8,10],'odd':[1,3,5,7,9]})
df.head()

even  odd
0     2    1
1     4    3
2     6    5
3     8    7
4    10    9

In [ ]:
X = df[['even']]
y = df[['odd']]

In [ ]:
scalar = StandardScaler()
X_scaled = scalar.fit_transform(X)

In [ ]:
mlp = MLPRegressor(hidden_layer_sizes=(4),activation='relu',max_iter=500)

In [ ]:
mlp.fit(X_scaled,y)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=4, max_iter=500)

In [ ]:
iter = 2
for i in range(iter):
  mlp.fit(X_scaled,y)
  hidden_layer_weights = mlp.coefs_[0]
  hidden_layer_bias = mlp.intercepts_[0]
  output_layer_weights = mlp.coefs_[1]
  output_layer_bias = mlp.intercepts_[1]
  print(hidden_layer_weights)
  print(hidden_layer_bias)
  print(output_layer_weights)
  print(output_layer_bias)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-0.95253846  0.08445732  1.35155853 -1.36296886]]
[-0.67397759  0.31447976 -0.08569598 -0.24435024]
[[-0.40170641]
 [ 0.13598623]
 [ 1.56773917]
 [ 0.96871239]]
[0.30765024]
[[-1.07136914 -0.00254072  1.56911837 -0.76448449]]
[-0.6955969   1.16094846  0.73607256 -0.27680999]
[[-1.17531801]
 [ 1.63222435]
 [ 0.86248472]
 [-0.04743257]]
[0.5504278]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
df = pd.DataFrame({'Day':[1,2,3,4,5],'night':[6,7,8,9,10]})
df.head()

Day  night
0    1      6
1    2      7
2    3      8
3    4      9
4    5     10

In [ ]:
X = df[['Day']]
y = df[['night']]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
mlp = MLPRegressor(hidden_layer_sizes=(5),activation='relu',max_iter=10)

In [ ]:
mlp.fit(X_scaled,y)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=5, max_iter=10)

In [ ]:
iter = 5
for i in range(iter):
  mlp.fit(X_scaled,y)
  hidden_layer_weights = mlp.coefs_[0]
  hidden_layer_bias = mlp.intercepts_[0]
  output_layer_weights = mlp.coefs_[1]
  output_layer_bias = mlp.intercepts_[1]
  print(hidden_layer_weights)
  print(hidden_layer_bias)
  print(output_layer_weights)
  print(output_layer_bias)

[[-0.16697174  0.10975333 -0.53739017  0.44452988  0.9830729 ]]
[ 0.8504995  -0.96451075  0.44419261 -0.46427775  0.20849222]
[[-0.82838513]
 [ 0.35862124]
 [ 0.43151011]
 [ 0.79578375]
 [-0.50144539]]
[-0.06877024]
[[ 0.81577212  0.7614441  -0.24616999 -0.29204109  0.97918352]]
[-0.95274689 -0.04790775  0.22989895 -0.61482655 -0.65783858]
[[-0.48816278]
 [-0.64910038]
 [ 0.69198894]
 [-0.82511873]
 [ 0.02221873]]
[-0.84116861]
[[ 0.90991472 -0.02689182 -0.56637078  0.62988348 -0.00136877]]
[-0.4245105  -0.70015313 -0.66433825  0.3756261  -0.95407093]
[[-0.88135488]
 [-0.71565748]
 [ 0.60796146]
 [-0.82618392]
 [-0.17723187]]
[0.31081787]
[[-0.87128179  0.72717633 -0.64354327 -0.41031637  0.84104498]]
[ 0.21574513 -0.48791833  0.34261639 -0.52574224 -0.49015012]
[[ 0.29701651]
 [-0.35398135]
 [ 0.17770679]
 [-0.86251846]
 [ 0.88299625]]
[-0.01258756]
[[ 0.62723069 -0.78604421 -0.19545708 -0.48195328 -0.54551276]]
[ 0.08323352  0.66280934  0.19420152 -0.29320825  0.99948863]
[[ 0.691676

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converge

In [ ]:
from mlxtend.data import iris_data
from mlxtend.plotting import plot_decision_regions
import matplotlib.pyplot as plt
from mlxtend.classifier import Perceptron
import numpy as np

In [ ]:
X,y = iris_data()

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
X = X[:,[0,3]]
X

array([[5.1, 0.2],
       [4.9, 0.2],
       [4.7, 0.2],
       [4.6, 0.2],
       [5. , 0.2],
       [5.4, 0.4],
       [4.6, 0.3],
       [5. , 0.2],
       [4.4, 0.2],
       [4.9, 0.1],
       [5.4, 0.2],
       [4.8, 0.2],
       [4.8, 0.1],
       [4.3, 0.1],
       [5.8, 0.2],
       [5.7, 0.4],
       [5.4, 0.4],
       [5.1, 0.3],
       [5.7, 0.3],
       [5.1, 0.3],
       [5.4, 0.2],
       [5.1, 0.4],
       [4.6, 0.2],
       [5.1, 0.5],
       [4.8, 0.2],
       [5. , 0.2],
       [5. , 0.4],
       [5.2, 0.2],
       [5.2, 0.2],
       [4.7, 0.2],
       [4.8, 0.2],
       [5.4, 0.4],
       [5.2, 0.1],
       [5.5, 0.2],
       [4.9, 0.1],
       [5. , 0.2],
       [5.5, 0.2],
       [4.9, 0.1],
       [4.4, 0.2],
       [5.1, 0.2],
       [5. , 0.3],
       [4.5, 0.3],
       [4.4, 0.2],
       [5. , 0.6],
       [5.1, 0.4],
       [4.8, 0.3],
       [5.1, 0.2],
       [4.6, 0.2],
       [5.3, 0.2],
       [5. , 0.2],
       [7. , 1.4],
       [6.4, 1.5],
       [6.9,

In [ ]:
X = X[0:100]
y = y[0:100]

In [ ]:
X

array([[5.1, 0.2],
       [4.9, 0.2],
       [4.7, 0.2],
       [4.6, 0.2],
       [5. , 0.2],
       [5.4, 0.4],
       [4.6, 0.3],
       [5. , 0.2],
       [4.4, 0.2],
       [4.9, 0.1],
       [5.4, 0.2],
       [4.8, 0.2],
       [4.8, 0.1],
       [4.3, 0.1],
       [5.8, 0.2],
       [5.7, 0.4],
       [5.4, 0.4],
       [5.1, 0.3],
       [5.7, 0.3],
       [5.1, 0.3],
       [5.4, 0.2],
       [5.1, 0.4],
       [4.6, 0.2],
       [5.1, 0.5],
       [4.8, 0.2],
       [5. , 0.2],
       [5. , 0.4],
       [5.2, 0.2],
       [5.2, 0.2],
       [4.7, 0.2],
       [4.8, 0.2],
       [5.4, 0.4],
       [5.2, 0.1],
       [5.5, 0.2],
       [4.9, 0.1],
       [5. , 0.2],
       [5.5, 0.2],
       [4.9, 0.1],
       [4.4, 0.2],
       [5.1, 0.2],
       [5. , 0.3],
       [4.5, 0.3],
       [4.4, 0.2],
       [5. , 0.6],
       [5.1, 0.4],
       [4.8, 0.3],
       [5.1, 0.2],
       [4.6, 0.2],
       [5.3, 0.2],
       [5. , 0.2],
       [7. , 1.4],
       [6.4, 1.5],
       [6.9,

In [ ]:
X[:,0] = (X[:,0]-X[:,0].mean())/X[:,0].std()
X[:,1] = (X[:,1]-X[:,1].mean())/X[:,1].std()

In [ ]:
X

array([[-0.5810659 , -1.03824799],
       [-0.89430898, -1.03824799],
       [-1.20755205, -1.03824799],
       [-1.36417359, -1.03824799],
       [-0.73768744, -1.03824799],
       [-0.11120129, -0.68329141],
       [-1.36417359, -0.8607697 ],
       [-0.73768744, -1.03824799],
       [-1.67741667, -1.03824799],
       [-0.89430898, -1.21572628],
       [-0.11120129, -1.03824799],
       [-1.05093052, -1.03824799],
       [-1.05093052, -1.21572628],
       [-1.8340382 , -1.21572628],
       [ 0.51528486, -1.03824799],
       [ 0.35866332, -0.68329141],
       [-0.11120129, -0.68329141],
       [-0.5810659 , -0.8607697 ],
       [ 0.35866332, -0.8607697 ],
       [-0.5810659 , -0.8607697 ],
       [-0.11120129, -1.03824799],
       [-0.5810659 , -0.68329141],
       [-1.36417359, -1.03824799],
       [-0.5810659 , -0.50581312],
       [-1.05093052, -1.03824799],
       [-0.73768744, -1.03824799],
       [-0.73768744, -0.68329141],
       [-0.42444437, -1.03824799],
       [-0.42444437,

In [ ]:
pn = Perceptron(epochs =5,eta=0.05,random_seed=0)
pn.fit(X,y)

In [ ]:
print('weights',pn.w_)

weights [[-0.04500809]
 [ 0.11048855]]


In [ ]:
print('bias',pn.b_)

bias [0.]


In [ ]:
def perceptron_ex(X,weights,bias):
  output = np.dot(X,weights)+bias
  return np.where(output>=0.0,1,0)

In [ ]:
X_new = np.array([[0.5,-1.0]])
perceptron_ex(X_new,pn.w_,pn.b_)

array([[0]])